plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.teachingapp'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.teachingapp"
        minSdk 28
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_10
        targetCompatibility JavaVersion.VERSION_1_10
    }
    buildToolsVersion '34.0.0'
    packagingOptions {
        exclude "META-INF/DEPENDENCIES"
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation 'com.journeyapps:zxing-android-embedded:4.1.0'
    implementation 'com.journeyapps:zxing-android-embedded:4.1.0'
    implementation 'com.google.zxing:core:3.3.3'

    // https://mvnrepository.com/artifact/com.squareup.retrofit2/retrofit
    implementation group: 'com.squareup.retrofit2', name: 'retrofit', version: '2.9.0'
    // https://mvnrepository.com/artifact/com.squareup.retrofit2/converter-gson
    implementation group: 'com.squareup.retrofit2', name: 'converter-gson', version: '2.9.0'
    // https://mvnrepository.com/artifact/org.projectlombok/lombok
    compileOnly 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'
    // https://mvnrepository.com/artifact/org.mockito/mockito-core
    testImplementation group: 'org.mockito', name: 'mockito-core', version: '5.12.0'
    // https://mvnrepository.com/artifact/org.json/json
    implementation group: 'org.json', name: 'json', version: '20240303'

    implementation "androidx.cardview:cardview:1.0.0"

    implementation "com.jjoe64:graphview:4.2.2"

    androidTestImplementation "androidx.test:runner:1.6.2"
    androidTestImplementation "androidx.test:rules:1.6.1"
    // Optional -- UI testing with Espresso
    androidTestImplementation "androidx.test.espresso:espresso-core:3.6.1"
    // Optional -- UI testing with UI Automator
    androidTestImplementation "androidx.test.uiautomator:uiautomator:2.3.0"
    // Optional -- UI testing with Compose
    androidTestImplementation "androidx.compose.ui:ui-test-junit4:1.7.6"
    androidTestImplementation 'androidx.test.espresso:espresso-intents:3.6.1'
    // https://mvnrepository.com/artifact/org.mockito/mockito-core
    implementation group: 'org.mockito', name: 'mockito-android', version: '5.14.2'
    // https://mvnrepository.com/artifact/org.mockito/mockito-junit-jupiter
    testImplementation  group: 'org.mockito', name: 'mockito-junit-jupiter', version: '5.12.0'
    androidTestImplementation "com.squareup.okhttp3:mockwebserver:4.11.0"
    implementation "com.squareup.okhttp3:okhttp:4.11.0"
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.18.2'
}